language: python
python:
    - "3.6"
install:
    - "pip install coverage"
    - "pip install coveralls"
script:
    - "coverage run --source=url-normalize setup.py test"
after_success:
    coveralls
