name: Deploy

on:
  push:
    tags: ['v*']
env:
  LATEST_PY_VERSION: '3.11'

jobs:
  # Deploy stable builds on tags only
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.LATEST_PY_VERSION }}
      - uses: snok/install-poetry@v1.3
        with:
          virtualenvs-in-project: true

      - name: Build package distributions
        run: poetry build

      # TODO
      # - name: Publish package distributions to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
